import { useState } from "react";
import {
  FileText,
  Printer,
  Copy,
  Check,
  Building2,
  GitBranch,
  Layers,
  BarChart3,
  Calendar,
} from "lucide-react";
import { useDashboardOverview } from "@/hooks/useDashboardOverview";
import { useProject } from "@/context/ProjectContext";

export function ReportsPage() {
  const { activeProject } = useProject();
  const data = useDashboardOverview();
  const [selectedReportType, setSelectedReportType] = useState<string>("executive");
  const [copied, setCopied] = useState(false);

  const reportDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const handlePrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    const md = `# Coodara Architecture Health Audit Report
**Organization**: ${activeProject?.name ?? "Coodara Organization"}
**Date**: ${reportDate}
**Overall Architecture Score**: ${data.healthScore}/100 (${data.healthLabel})
**Monitored Repositories**: ${data.totalRepos} (${data.analyzedReposCount} analyzed)
**Codebase Volume**: ${data.totalLoc.toLocaleString()} LOC | ${data.totalFiles} files | ${data.totalClasses} classes | ${data.totalFunctions} functions

## Structural Metrics
- Maintainability Index: ${data.healthBreakdown.maintainability}/100
- Complexity Score: ${data.healthBreakdown.complexity}/100
- Coupling Factor: ${data.healthBreakdown.coupling}/100
- Modularity Score: ${data.healthBreakdown.modularity}/100

## Identified Risks (${data.allIssues.length} total)
${
  data.allIssues.length === 0
    ? "- No critical architectural risks or circular dependencies detected."
    : data.allIssues.map((i) => `- [${i.issue.severity.toUpperCase()}] ${i.repoName} (${i.issue.type}): ${i.issue.title || i.issue.description}`).join("\n")
}

## Detected Technologies
${data.technologies.map((t) => `- ${t.name} (${t.count} repositories, ${int(t.confidence * 100)}% conf)`).join("\n")}

Generated by Coodara Architecture Intelligence.`;

    void navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  function int(val: number) {
    return Math.round(val);
  }

  if (data.loading) {
    return (
      <div className="flex h-64 items-center justify-center text-[13px] text-[var(--cd-ink-soft)]">
        Compiling architecture reports...
      </div>
    );
  }

  return (
    <div className="min-h-[calc(100vh-56px)] bg-[var(--cd-bg)] p-4 sm:p-6 space-y-5">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--cd-border-soft)] pb-4 print:hidden">
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[var(--cd-accent-soft)] text-[var(--cd-accent)]">
            <FileText className="h-5 w-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-[18px] font-semibold text-[var(--cd-ink)]">
                Architecture Reports & Audits
              </h1>
              <span className="rounded-full bg-[var(--cd-sunken)] px-2.5 py-0.5 text-[11px] font-medium text-[var(--cd-ink-soft)]">
                {activeProject?.name ?? "Organization"}
              </span>
            </div>
            <p className="text-[12px] text-[var(--cd-ink-faint)]">
              Export executive architecture audits, governance compliance, and refactoring scorecards.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyMarkdown}
            className="cursor-pointer flex items-center gap-1.5 rounded-lg border border-[var(--cd-border)] bg-[var(--cd-surface)] px-3 py-2 text-[12px] font-medium text-[var(--cd-ink)] shadow-sm hover:bg-[var(--cd-sunken)] transition-colors"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-[var(--cd-good)]" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? "Copied Markdown" : "Copy Markdown"}
          </button>

          <button
            onClick={handlePrint}
            className="cursor-pointer flex items-center gap-1.5 rounded-lg bg-[var(--cd-accent)] px-3.5 py-2 text-[12px] font-medium text-white shadow-sm hover:bg-[var(--cd-accent-hover)] transition-colors"
          >
            <Printer className="h-3.5 w-3.5" />
            Print / Save PDF
          </button>
        </div>
      </div>

      {/* Report Selector Pills (Print Hidden) */}
      <div className="flex flex-wrap gap-2 print:hidden">
        {[
          { id: "executive", label: "Executive Health Audit" },
          { id: "modularity", label: "Modularity & Coupling" },
          { id: "techstack", label: "Technology Inventory" },
          { id: "debt", label: "Technical Debt & Risks" },
        ].map((item) => (
          <button
            key={item.id}
            onClick={() => setSelectedReportType(item.id)}
            className={`cursor-pointer rounded-lg px-3 py-1.5 text-[12px] font-medium transition-all ${
              selectedReportType === item.id
                ? "bg-[var(--cd-accent)] text-white shadow-sm"
                : "border border-[var(--cd-border)] bg-[var(--cd-surface)] text-[var(--cd-ink-soft)] hover:bg-[var(--cd-sunken)]"
            }`}
          >
            {item.label}
          </button>
        ))}
      </div>

      {/* Printable Report Document Sheet */}
      <div className="rounded-2xl border border-[var(--cd-border)] bg-[var(--cd-surface)] p-6 sm:p-8 shadow-sm print:border-none print:p-0 space-y-6">
        {/* Document Header */}
        <div className="flex flex-wrap items-start justify-between gap-4 border-b border-[var(--cd-border-soft)] pb-6">
          <div>
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-bold uppercase tracking-widest text-[var(--cd-accent)]">
                Coodara Architecture Intelligence
              </span>
            </div>
            <h2 className="mt-1 text-2xl font-bold text-[var(--cd-ink)]">
              {selectedReportType === "executive"
                ? "Executive Architecture Health Audit"
                : selectedReportType === "modularity"
                ? "Modularity, Coupling & Cohesion Analysis"
                : selectedReportType === "techstack"
                ? "Organization Technology & Package Inventory"
                : "Technical Debt & Architecture Risk Report"}
            </h2>
            <div className="mt-2 flex flex-wrap items-center gap-4 text-[12px] text-[var(--cd-ink-faint)]">
              <span className="flex items-center gap-1 font-medium text-[var(--cd-ink)]">
                <Building2 className="h-3.5 w-3.5 text-[var(--cd-ink-soft)]" />
                {activeProject?.name ?? "Organization Portfolio"}
              </span>
              <span className="flex items-center gap-1">
                <Calendar className="h-3.5 w-3.5" />
                {reportDate}
              </span>
              <span>•</span>
              <span>Scope: {data.totalRepos} Repositories</span>
            </div>
          </div>

          <div className="flex flex-col items-end">
            <div className="text-[11px] font-semibold text-[var(--cd-ink-faint)] uppercase tracking-wider">
              Health Status
            </div>
            <div className="flex items-center gap-2 mt-1">
              <span className="text-3xl font-bold font-mono text-[var(--cd-ink)]">
                {data.healthScore}
              </span>
              <span className="text-sm font-semibold text-[var(--cd-ink-faint)]">/100</span>
            </div>
            <span
              className={`mt-1 rounded-full px-2.5 py-0.5 text-[10.5px] font-bold uppercase tracking-wide ${
                data.healthLabel === "Healthy"
                  ? "bg-[var(--cd-good-soft)] text-[var(--cd-good)]"
                  : "bg-[var(--cd-warn-soft)] text-[var(--cd-warn)]"
              }`}
            >
              {data.healthLabel}
            </span>
          </div>
        </div>

        {/* Key Metrics Grid */}
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          <div className="rounded-xl bg-[var(--cd-sunken)] p-3.5">
            <div className="text-[11px] font-medium text-[var(--cd-ink-faint)]">Total Code Volume</div>
            <div className="mt-1 text-xl font-bold font-mono text-[var(--cd-ink)]">
              {data.totalLoc.toLocaleString()} <span className="text-xs font-normal text-[var(--cd-ink-faint)]">LOC</span>
            </div>
            <div className="text-[10.5px] text-[var(--cd-ink-faint)]">{data.totalFiles} files across codebase</div>
          </div>

          <div className="rounded-xl bg-[var(--cd-sunken)] p-3.5">
            <div className="text-[11px] font-medium text-[var(--cd-ink-faint)]">AST Constructs</div>
            <div className="mt-1 text-xl font-bold font-mono text-[var(--cd-ink)]">
              {data.totalFunctions.toLocaleString()} <span className="text-xs font-normal text-[var(--cd-ink-faint)]">fn</span>
            </div>
            <div className="text-[10.5px] text-[var(--cd-ink-faint)]">{data.totalClasses} classes parsed</div>
          </div>

          <div className="rounded-xl bg-[var(--cd-sunken)] p-3.5">
            <div className="text-[11px] font-medium text-[var(--cd-ink-faint)]">Maintainability</div>
            <div className="mt-1 text-xl font-bold font-mono text-[var(--cd-good)]">
              {data.healthBreakdown.maintainability} <span className="text-xs font-normal text-[var(--cd-ink-faint)]">/100</span>
            </div>
            <div className="text-[10.5px] text-[var(--cd-ink-faint)]">Halstead & Cyclomatic balance</div>
          </div>

          <div className="rounded-xl bg-[var(--cd-sunken)] p-3.5">
            <div className="text-[11px] font-medium text-[var(--cd-ink-faint)]">Active Risks</div>
            <div className="mt-1 text-xl font-bold font-mono text-[var(--cd-ink)]">
              {data.allIssues.length} <span className="text-xs font-normal text-[var(--cd-ink-faint)]">issues</span>
            </div>
            <div className="text-[10.5px] text-[var(--cd-ink-faint)]">{data.criticalFindingsCount} critical blockers</div>
          </div>
        </div>

        {/* Section 1: Architecture Breakdown */}
        <div className="space-y-3">
          <h3 className="text-[14px] font-semibold text-[var(--cd-ink)] flex items-center gap-1.5">
            <BarChart3 className="h-4 w-4 text-[var(--cd-accent)]" />
            Structural Health Indices
          </h3>

          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            <div className="rounded-xl border border-[var(--cd-border-soft)] p-3.5 space-y-2">
              <div className="flex justify-between text-[12px]">
                <span className="font-medium text-[var(--cd-ink)]">Maintainability Index</span>
                <span className="font-mono font-bold">{data.healthBreakdown.maintainability}%</span>
              </div>
              <div className="h-1.5 w-full rounded-full bg-[var(--cd-sunken)]">
                <div
                  className="h-full rounded-full bg-[var(--cd-good)]"
                  style={{ width: `${data.healthBreakdown.maintainability}%` }}
                />
              </div>
              <p className="text-[11px] text-[var(--cd-ink-faint)]">
                Measures ease of refactoring and code comprehension.
              </p>
            </div>

            <div className="rounded-xl border border-[var(--cd-border-soft)] p-3.5 space-y-2">
              <div className="flex justify-between text-[12px]">
                <span className="font-medium text-[var(--cd-ink)]">Modularity & Layering</span>
                <span className="font-mono font-bold">{data.healthBreakdown.modularity}%</span>
              </div>
              <div className="h-1.5 w-full rounded-full bg-[var(--cd-sunken)]">
                <div
                  className="h-full rounded-full bg-[var(--cd-accent)]"
                  style={{ width: `${data.healthBreakdown.modularity}%` }}
                />
              </div>
              <p className="text-[11px] text-[var(--cd-ink-faint)]">
                Evaluates separation between presentation, services, and persistence layers.
              </p>
            </div>

            <div className="rounded-xl border border-[var(--cd-border-soft)] p-3.5 space-y-2">
              <div className="flex justify-between text-[12px]">
                <span className="font-medium text-[var(--cd-ink)]">Coupling Isolation</span>
                <span className="font-mono font-bold">{data.healthBreakdown.coupling}%</span>
              </div>
              <div className="h-1.5 w-full rounded-full bg-[var(--cd-sunken)]">
                <div
                  className="h-full rounded-full bg-[var(--cd-good)]"
                  style={{ width: `${data.healthBreakdown.coupling}%` }}
                />
              </div>
              <p className="text-[11px] text-[var(--cd-ink-faint)]">
                Low fan-out indicates clean, independent modules.
              </p>
            </div>

            <div className="rounded-xl border border-[var(--cd-border-soft)] p-3.5 space-y-2">
              <div className="flex justify-between text-[12px]">
                <span className="font-medium text-[var(--cd-ink)]">Complexity Control</span>
                <span className="font-mono font-bold">{data.healthBreakdown.complexity}%</span>
              </div>
              <div className="h-1.5 w-full rounded-full bg-[var(--cd-sunken)]">
                <div
                  className="h-full rounded-full bg-[var(--cd-warn)]"
                  style={{ width: `${data.healthBreakdown.complexity}%` }}
                />
              </div>
              <p className="text-[11px] text-[var(--cd-ink-faint)]">
                Identifies deep branch nesting and complex logic blocks.
              </p>
            </div>
          </div>
        </div>

        {/* Section 2: Repositories Portfolio Table */}
        <div className="space-y-3">
          <h3 className="text-[14px] font-semibold text-[var(--cd-ink)] flex items-center gap-1.5">
            <GitBranch className="h-4 w-4 text-[var(--cd-accent)]" />
            Repository Portfolio Breakdown
          </h3>

          <div className="overflow-x-auto rounded-xl border border-[var(--cd-border-soft)]">
            <table className="w-full text-left text-[12px]">
              <thead className="border-b border-[var(--cd-border-soft)] bg-[var(--cd-sunken)] text-[11px] font-semibold text-[var(--cd-ink-faint)] uppercase">
                <tr>
                  <th className="px-4 py-2.5">Repository</th>
                  <th className="px-4 py-2.5">Language</th>
                  <th className="px-4 py-2.5">LOC</th>
                  <th className="px-4 py-2.5">Architecture Score</th>
                  <th className="px-4 py-2.5">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[var(--cd-border-soft)] text-[var(--cd-ink)]">
                {data.repoData.map(({ repo, result, architecture }) => {
                  const score = architecture?.summary?.health_score;
                  const loc = result?.metrics?.loc ?? 0;
                  return (
                    <tr key={repo.id} className="hover:bg-[var(--cd-sunken)]/50">
                      <td className="px-4 py-2.5 font-medium">{repo.name}</td>
                      <td className="px-4 py-2.5 text-[var(--cd-ink-faint)]">
                        {repo.primary_language || "Multi-language"}
                      </td>
                      <td className="px-4 py-2.5 font-mono">{loc.toLocaleString()}</td>
                      <td className="px-4 py-2.5 font-mono">
                        {score != null ? `${score.toFixed(1)}/100` : "Not analyzed"}
                      </td>
                      <td className="px-4 py-2.5">
                        <span className="rounded bg-[var(--cd-good-soft)] px-2 py-0.5 text-[10.5px] font-semibold text-[var(--cd-good)]">
                          Active
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* Section 3: Technology Inventory */}
        <div className="space-y-3">
          <h3 className="text-[14px] font-semibold text-[var(--cd-ink)] flex items-center gap-1.5">
            <Layers className="h-4 w-4 text-[var(--cd-accent)]" />
            Detected Frameworks & Technology Stack
          </h3>

          <div className="flex flex-wrap gap-2">
            {data.technologies.map((tech) => (
              <div
                key={tech.name}
                className="flex items-center gap-2 rounded-lg border border-[var(--cd-border-soft)] bg-[var(--cd-sunken)] px-3 py-1.5 text-[12px]"
              >
                <span className="font-semibold text-[var(--cd-ink)]">{tech.name}</span>
                <span className="rounded bg-[var(--cd-surface)] px-1.5 py-0.2 text-[10.5px] font-mono text-[var(--cd-ink-faint)]">
                  {tech.count} {tech.count === 1 ? "repo" : "repos"}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="border-t border-[var(--cd-border-soft)] pt-4 text-[11px] text-[var(--cd-ink-faint)] flex items-center justify-between">
          <span>Generated by Coodara Autonomous Architecture Platform</span>
          <span>Confidential • Internal Engineering Audit</span>
        </div>
      </div>
    </div>
  );
}
