"""add encrypted github credential

Revision ID: 0e0e4270c22c
Revises: 202b1e0da9da
Create Date: 2026-08-10 18:36:13.361936

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0e0e4270c22c'
down_revision: str | Sequence[str] | None = '202b1e0da9da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token_encrypted', sa.Text(), nullable=True))
    op.drop_constraint(op.f('users_github_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.create_unique_constraint(op.f('users_github_id_key'), 'users', ['github_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'github_access_token_encrypted')
    # ### end Alembic commands ###
