"""expand repository model

Revision ID: 202b1e0da9da
Revises: f7dfaced807e
Create Date: 2026-08-08 10:03:38.021924

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '202b1e0da9da'
down_revision: str | Sequence[str] | None = 'f7dfaced807e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('repositories', 'clone_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('repositories', 'html_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.drop_index(op.f('ix_repositories_github_repository_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_status'), table_name='repositories')
    op.drop_constraint(op.f('uq_repository_github'), 'repositories', type_='unique')
    op.create_index(op.f('ix_repositories_github_id'), 'repositories', ['github_id'], unique=False)
    op.create_unique_constraint('uq_repository_organization_github', 'repositories', ['organization_id', 'github_id'])
    op.drop_column('repositories', 'github_repository_id')
    op.drop_column('repositories', 'status')
    op.drop_column('repositories', 'archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('repositories', sa.Column('status', postgresql.ENUM('IMPORTED', 'READY', 'ANALYZING', 'ACTIVE', 'FAILED', 'ARCHIVED', name='repository_status'), autoincrement=False, nullable=False))
    op.add_column('repositories', sa.Column('github_repository_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_repository_organization_github', 'repositories', type_='unique')
    op.drop_index(op.f('ix_repositories_github_id'), table_name='repositories')
    op.create_unique_constraint(op.f('uq_repository_github'), 'repositories', ['organization_id', 'github_repository_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_repositories_status'), 'repositories', ['status'], unique=False)
    op.create_index(op.f('ix_repositories_github_repository_id'), 'repositories', ['github_repository_id'], unique=False)
    op.alter_column('repositories', 'html_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('repositories', 'clone_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('repositories', 'full_name',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
