"""Add repository analysis models

Revision ID: 20e836edd355
Revises: 280d3ceef1e3
Create Date: 2026-08-18 14:52:24.518112

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20e836edd355'
down_revision: str | Sequence[str] | None = '280d3ceef1e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'completed', 'failed', 'cancelled', name='analysis_status'), server_default='pending', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_repository_id'), 'analysis_jobs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_job_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_analysis_job_id'), 'analysis_results', ['analysis_job_id'], unique=True)
    op.create_table('dependency_graphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_result_id', sa.Integer(), nullable=False),
    sa.Column('graph_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_graphs_analysis_result_id'), 'dependency_graphs', ['analysis_result_id'], unique=True)
    op.create_table('detected_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_result_id', sa.Integer(), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_result_id', 'technology', name='uq_detected_technology_result_technology')
    )
    op.create_index(op.f('ix_detected_technologies_analysis_result_id'), 'detected_technologies', ['analysis_result_id'], unique=False)
    op.create_table('repository_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_result_id', sa.Integer(), nullable=False),
    sa.Column('loc', sa.Integer(), server_default='0', nullable=False),
    sa.Column('files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('classes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('functions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('complexity', sa.Float(), nullable=True),
    sa.Column('maintainability', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_metrics_analysis_result_id'), 'repository_metrics', ['analysis_result_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_metrics_analysis_result_id'), table_name='repository_metrics')
    op.drop_table('repository_metrics')
    op.drop_index(op.f('ix_detected_technologies_analysis_result_id'), table_name='detected_technologies')
    op.drop_table('detected_technologies')
    op.drop_index(op.f('ix_dependency_graphs_analysis_result_id'), table_name='dependency_graphs')
    op.drop_table('dependency_graphs')
    op.drop_index(op.f('ix_analysis_results_analysis_job_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_repository_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
