"""use bigint for repository github id

Revision ID: 280d3ceef1e3
Revises: 0e0e4270c22c
Create Date: 2026-08-16 14:59:50.348092

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '280d3ceef1e3'
down_revision: str | Sequence[str] | None = '0e0e4270c22c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'github_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_repositories_github_id'), table_name='repositories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_repositories_github_id'), 'repositories', ['github_id'], unique=False)
    op.alter_column('repositories', 'github_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
