"""add_architecture_models

Revision ID: 2c8451c05279
Revises: 20e836edd355
Create Date: 2026-09-01 14:23:40.297344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8451c05279'
down_revision: Union[str, Sequence[str], None] = '20e836edd355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('analysis_result_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('graph', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_snapshots_analysis_result_id'), 'architecture_snapshots', ['analysis_result_id'], unique=True)
    op.create_index(op.f('ix_architecture_snapshots_repository_id'), 'architecture_snapshots', ['repository_id'], unique=False)
    op.create_table('architecture_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('architecture_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['architecture_snapshot_id'], ['architecture_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_issues_architecture_snapshot_id'), 'architecture_issues', ['architecture_snapshot_id'], unique=False)
    op.create_table('architecture_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('architecture_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['architecture_snapshot_id'], ['architecture_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_recommendations_architecture_snapshot_id'), 'architecture_recommendations', ['architecture_snapshot_id'], unique=False)
    op.create_table('architecture_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('architecture_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('maintainability', sa.Float(), nullable=False),
    sa.Column('coupling', sa.Float(), nullable=False),
    sa.Column('cohesion', sa.Float(), nullable=False),
    sa.Column('complexity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['architecture_snapshot_id'], ['architecture_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_architecture_scores_architecture_snapshot_id'), 'architecture_scores', ['architecture_snapshot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_architecture_scores_architecture_snapshot_id'), table_name='architecture_scores')
    op.drop_table('architecture_scores')
    op.drop_index(op.f('ix_architecture_recommendations_architecture_snapshot_id'), table_name='architecture_recommendations')
    op.drop_table('architecture_recommendations')
    op.drop_index(op.f('ix_architecture_issues_architecture_snapshot_id'), table_name='architecture_issues')
    op.drop_table('architecture_issues')
    op.drop_index(op.f('ix_architecture_snapshots_repository_id'), table_name='architecture_snapshots')
    op.drop_index(op.f('ix_architecture_snapshots_analysis_result_id'), table_name='architecture_snapshots')
    op.drop_table('architecture_snapshots')
    # ### end Alembic commands ###
